### ISSUE TITLE
Cannot get the functions correctly

### ISSUE THREAD

**Issue by f10atin9** [OpenFunction/cli#38]
The ` ofn get ` command does not get the function correctly.
![image](https://user-images.githubusercontent.com/36705019/160522998-2fbcd977-2cf9-4a78-8e40-0ab984e5ab92.png)

**Comment by tpiperatgod** [comment]
It seems that we need to upgrade the version of OpenFunction in Cli.

From `v1alpha1` to `v1beta1`.

**Comment by benjaminhuo** [comment]
Thanks for taking this @f10atin9.
Previously @wentevill add the client library in this cli tool, the client code is implemented in this cli tool.

But a better way is to add client library in the main repo and that's why https://github.com/OpenFunction/OpenFunction/pull/176 and https://github.com/OpenFunction/OpenFunction/pull/243 are created for.

So going forward, we may need to replace the client library in this cli with the one in the main repo. Use the client library in the main repo to implement functions like `ofn get fn`

**Comment by benjaminhuo** [comment]
@wentevill has created a PR for this https://github.com/OpenFunction/cli/pull/41 
Close this issue for now.
